language: cpp

env:
    matrix:
        - CONFIGURATION=Debug
        - CONFIGURATION=Release

install:
    - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update
    - sudo apt-get install qt5-default

before_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION

script:
    - cmake --build .
    - ctest -V
