language: cpp

before_install:
     # gcc 4.9
     - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
     # cmake 2.8.11
     - sudo add-apt-repository --yes ppa:kalakris/cmake
     # repository for qt5
     - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
     - sudo apt-get update -qq
install:     
     - sudo apt-get install qtbase5-dev qtdeclarative5-dev qtdeclarative5-test-plugin libqt5quick5 libqt5qml5 qtdeclarative5-qtquick2-plugin qt5-default qttools5-dev-tools
     - sudo apt-get install cmake
     - sudo apt-get install liblzma-dev liblzo2-dev
     - sudo apt-get install libboost-all-dev
     # GCC / Clang (Needed until Travis CI updates to Ubuntu 14.04+)
     - sudo apt-get install -qq --force-yes g++-4.9
     - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
     - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
     - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
     # LCOV (Needed until Travis CI updates to Ubuntu 14.04+)
     - wget -O lcov.tar.gz http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
     - mkdir lcov
     - tar -xzf lcov.tar.gz -C ./lcov --strip-components=1
     - cd lcov
     - sudo make install
     - cd ..
     - rm -Rf lcov lcov.tar.gz
     # Start display server to run qmltests.
     - "export DISPLAY=:99.0"
     - "sh -e /etc/init.d/xvfb start"
     - gem install coveralls-lcov

before_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
    - cmake --build .
    - ctest -V

after_success:
    - lcov --directory src --capture --output-file coverage.info
    - lcov --remove coverage.info '*/*build*/*' '*/Qt/*' '*/3rdparty/*' 'test/*' '/usr/*' --output-file coverage.info.cleaned
    - lcov --list coverage.info
    - coveralls-lcov coverage.info

