language: cpp

env:
    matrix:
        - CONFIGURATION=Debug
        - CONFIGURATION=Release

before_install:
     - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
     - sudo apt-get update -qq
     - sudo apt-get install qtbase5-dev qtdeclarative5-dev
     - sudo apt-get install qt5-default qttools5-dev-tools

before_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION

script:
    - cmake --build .
    - ctest -V
